# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/swelistnaija
spring.datasource.username=postgres
spring.datasource.password=how
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Scheduler
spring.task.scheduling.enabled=true

# Resend
resend.api.key=your-resend-api-key-here

# Ingest API Key
ingest.api.key=your-secret-ingest-key-here