version = 5.5.0
archive_dir = /etc/letsencrypt/archive/swehub.name.ng
cert = /etc/letsencrypt/live/swehub.name.ng/cert.pem
privkey = /etc/letsencrypt/live/swehub.name.ng/privkey.pem
chain = /etc/letsencrypt/live/swehub.name.ng/chain.pem
fullchain = /etc/letsencrypt/live/swehub.name.ng/fullchain.pem
[renewalparams]
account = 255564917944f60714e51fd90a8f2fc3
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
